name: Build LLVM nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'

jobs:

  CI-LLVM-nightly:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:rolling
    steps:
      - run: apt-get update
      - run: apt-get -qq install -y gcc g++ wget lsb-release wget software-properties-common gnupg git cmake flex python3-pebble python3-psutil python3-chardet python3-pytest vim unifdef
      - run: wget https://apt.llvm.org/llvm.sh
      - run: chmod +x llvm.sh
      - run: ./llvm.sh 16
      - run: apt-get install -y bolt-16 clang-16 libclang-common-16-dev libclang-16-dev mlir-16-tools llvm-16-tools libclang-common-16-dev libclang-16-dev libclang1-16 clang-format-16 python3-clang-16 clangd-16 clang-tidy-16 libomp-16-dev
      # TODO: fix it
      - run: ln -s /usr/lib/x86_64-linux-gnu/libclang-16.so.16.0.0 /usr/lib/x86_64-linux-gnu/libclang-16.so.1
      - uses: actions/checkout@v3
      - run: mkdir objdir
      - run: cmake ..
        working-directory: objdir
      - run: make -j`nproc` VERBOSE=1
        working-directory: objdir
      - run: pytest
        working-directory: objdir
